/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class ByteArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ByteArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ByteArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_ByteArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean Allocate(long length) {
    return fgbd4jJNI.ByteArray_Allocate(swigCPtr, this, length);
  }

  public ByteArray(long length) {
    this(fgbd4jJNI.new_ByteArray__SWIG_0(length), true);
  }

  public ByteArray() {
    this(fgbd4jJNI.new_ByteArray__SWIG_1(), true);
  }

  public void setByteArray(SWIGTYPE_p_unsigned_char value) {
    fgbd4jJNI.ByteArray_byteArray_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getByteArray() {
    long cPtr = fgbd4jJNI.ByteArray_byteArray_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setAllocatedLength(long value) {
    fgbd4jJNI.ByteArray_allocatedLength_set(swigCPtr, this, value);
  }

  public long getAllocatedLength() {
    return fgbd4jJNI.ByteArray_allocatedLength_get(swigCPtr, this);
  }

  public void setInUseLength(long value) {
    fgbd4jJNI.ByteArray_inUseLength_set(swigCPtr, this, value);
  }

  public long getInUseLength() {
    return fgbd4jJNI.ByteArray_inUseLength_get(swigCPtr, this);
  }

}
