/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class ByteArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ByteArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ByteArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_ByteArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ByteArray(long length) {
    this(fgbd4jJNI.new_ByteArray__SWIG_0(length), true);
  }

  public ByteArray() {
    this(fgbd4jJNI.new_ByteArray__SWIG_1(), true);
  }

  public void setBuffer(byte[] ByteArrayIN) {
    fgbd4jJNI.ByteArray_setBuffer(swigCPtr, this, ByteArrayIN);
  }

  public byte[] getBuffer() {
    return fgbd4jJNI.ByteArray_getBuffer(swigCPtr, this);
  }

}
