/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class ce_time {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ce_time(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ce_time obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_ce_time(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTm_sec(int value) {
    fgbd4jJNI.ce_time_tm_sec_set(swigCPtr, this, value);
  }

  public int getTm_sec() {
    return fgbd4jJNI.ce_time_tm_sec_get(swigCPtr, this);
  }

  public void setTm_min(int value) {
    fgbd4jJNI.ce_time_tm_min_set(swigCPtr, this, value);
  }

  public int getTm_min() {
    return fgbd4jJNI.ce_time_tm_min_get(swigCPtr, this);
  }

  public void setTm_hour(int value) {
    fgbd4jJNI.ce_time_tm_hour_set(swigCPtr, this, value);
  }

  public int getTm_hour() {
    return fgbd4jJNI.ce_time_tm_hour_get(swigCPtr, this);
  }

  public void setTm_mday(int value) {
    fgbd4jJNI.ce_time_tm_mday_set(swigCPtr, this, value);
  }

  public int getTm_mday() {
    return fgbd4jJNI.ce_time_tm_mday_get(swigCPtr, this);
  }

  public void setTm_mon(int value) {
    fgbd4jJNI.ce_time_tm_mon_set(swigCPtr, this, value);
  }

  public int getTm_mon() {
    return fgbd4jJNI.ce_time_tm_mon_get(swigCPtr, this);
  }

  public void setTm_year(int value) {
    fgbd4jJNI.ce_time_tm_year_set(swigCPtr, this, value);
  }

  public int getTm_year() {
    return fgbd4jJNI.ce_time_tm_year_get(swigCPtr, this);
  }

  public void setTm_wday(int value) {
    fgbd4jJNI.ce_time_tm_wday_set(swigCPtr, this, value);
  }

  public int getTm_wday() {
    return fgbd4jJNI.ce_time_tm_wday_get(swigCPtr, this);
  }

  public void setTm_yday(int value) {
    fgbd4jJNI.ce_time_tm_yday_set(swigCPtr, this, value);
  }

  public int getTm_yday() {
    return fgbd4jJNI.ce_time_tm_yday_get(swigCPtr, this);
  }

  public void setTm_isdst(int value) {
    fgbd4jJNI.ce_time_tm_isdst_set(swigCPtr, this, value);
  }

  public int getTm_isdst() {
    return fgbd4jJNI.ce_time_tm_isdst_get(swigCPtr, this);
  }

  public ce_time() {
    this(fgbd4jJNI.new_ce_time(), true);
  }

}
