/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class CircularArcCurve extends Curve {
  private transient long swigCPtr;

  protected CircularArcCurve(long cPtr, boolean cMemoryOwn) {
    super(fgbd4jJNI.CircularArcCurve_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CircularArcCurve obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_CircularArcCurve(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setCenterPoint(Point value) {
    fgbd4jJNI.CircularArcCurve_centerPoint_set(swigCPtr, this, Point.getCPtr(value), value);
  }

  public Point getCenterPoint() {
    long cPtr = fgbd4jJNI.CircularArcCurve_centerPoint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Point(cPtr, false);
  }

  public void setAngles(SWIGTYPE_p_double value) {
    fgbd4jJNI.CircularArcCurve_angles_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getAngles() {
    long cPtr = fgbd4jJNI.CircularArcCurve_angles_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setBits(int value) {
    fgbd4jJNI.CircularArcCurve_bits_set(swigCPtr, this, value);
  }

  public int getBits() {
    return fgbd4jJNI.CircularArcCurve_bits_get(swigCPtr, this);
  }

}
