/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class EnumSpatialReferenceInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EnumSpatialReferenceInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EnumSpatialReferenceInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_EnumSpatialReferenceInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EnumSpatialReferenceInfo() {
    this(fgbd4jJNI.new_EnumSpatialReferenceInfo(), true);
  }

  public boolean NextGeographicSpatialReference(SpatialReferenceInfo spatialReferenceInfo) {
    return fgbd4jJNI.EnumSpatialReferenceInfo_NextGeographicSpatialReference(swigCPtr, this, SpatialReferenceInfo.getCPtr(spatialReferenceInfo), spatialReferenceInfo);
  }

  public boolean NextProjectedSpatialReference(SpatialReferenceInfo spatialReferenceInfo) {
    return fgbd4jJNI.EnumSpatialReferenceInfo_NextProjectedSpatialReference(swigCPtr, this, SpatialReferenceInfo.getCPtr(spatialReferenceInfo), spatialReferenceInfo);
  }

  public void Reset() {
    fgbd4jJNI.EnumSpatialReferenceInfo_Reset(swigCPtr, this);
  }

}
