/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class EnumRows {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EnumRows(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EnumRows obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_EnumRows(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int Next(Row row) {
    return fgbd4jJNI.EnumRows_Next(swigCPtr, this, Row.getCPtr(row), row);
  }

  public void Close() {
    fgbd4jJNI.EnumRows_Close(swigCPtr, this);
  }

  public int GetFieldInformation(FieldInfo fieldInfo) {
    return fgbd4jJNI.EnumRows_GetFieldInformation(swigCPtr, this, FieldInfo.getCPtr(fieldInfo), fieldInfo);
  }

  public int GetFields(FieldDefs fieldDefs) {
    return fgbd4jJNI.EnumRows_GetFields(swigCPtr, this, FieldDefs.getCPtr(fieldDefs), fieldDefs);
  }

  public EnumRows() {
    this(fgbd4jJNI.new_EnumRows(), true);
  }

}
