/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class fgbd4j {
  public static int CreateGeodatabase(String path, Geodatabase geodatabase) {
    return fgbd4jJNI.CreateGeodatabase(path, Geodatabase.getCPtr(geodatabase), geodatabase);
  }

  public static int OpenGeodatabase(String path, Geodatabase geodatabase) {
    return fgbd4jJNI.OpenGeodatabase(path, Geodatabase.getCPtr(geodatabase), geodatabase);
  }

  public static int CloseGeodatabase(Geodatabase geodatabase) {
    return fgbd4jJNI.CloseGeodatabase(Geodatabase.getCPtr(geodatabase), geodatabase);
  }

  public static int DeleteGeodatabase(String path) {
    return fgbd4jJNI.DeleteGeodatabase(path);
  }

  public static int GetErrorDescription(int fgdbError, StringBuffer desc) {
    return fgbd4jJNI.GetErrorDescription(fgdbError, desc);
  }

  public static void GetErrorRecordCount(int[] recordCount) {
    fgbd4jJNI.GetErrorRecordCount(recordCount);
  }

  public static int GetErrorRecord(int recordNum, int[] fgdbError, StringBuffer errorDescription) {
    return fgbd4jJNI.GetErrorRecord(recordNum, fgdbError, errorDescription);
  }

  public static void ClearErrors() {
    fgbd4jJNI.ClearErrors();
  }

  public static boolean FindSpatialReferenceBySRID(int auth_srid, SpatialReferenceInfo spatialRef) {
    return fgbd4jJNI.FindSpatialReferenceBySRID(auth_srid, SpatialReferenceInfo.getCPtr(spatialRef), spatialRef);
  }

  public static boolean FindSpatialReferenceByName(String srname, SpatialReferenceInfo spatialRef) {
    return fgbd4jJNI.FindSpatialReferenceByName(srname, SpatialReferenceInfo.getCPtr(spatialRef), spatialRef);
  }

}
