/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class FieldInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FieldInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FieldInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_FieldInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int GetFieldCount(int[] fieldCount) {
    return fgbd4jJNI.FieldInfo_GetFieldCount(swigCPtr, this, fieldCount);
  }

  public int GetFieldName(int fieldNumber, StringBuffer fieldName) {
    return fgbd4jJNI.FieldInfo_GetFieldName(swigCPtr, this, fieldNumber, fieldName);
  }

  public int GetFieldType(int fieldNumber, int[] fieldType) {
    return fgbd4jJNI.FieldInfo_GetFieldType(swigCPtr, this, fieldNumber, fieldType);
  }

  public int GetFieldLength(int fieldNumber, int[] fieldLength) {
    return fgbd4jJNI.FieldInfo_GetFieldLength(swigCPtr, this, fieldNumber, fieldLength);
  }

  public int GetFieldIsNullable(int fieldNumber, boolean[] OUTPUT) {
    return fgbd4jJNI.FieldInfo_GetFieldIsNullable(swigCPtr, this, fieldNumber, OUTPUT);
  }

  public FieldInfo() {
    this(fgbd4jJNI.new_FieldInfo(), true);
  }

}
