/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class FieldDefs {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FieldDefs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FieldDefs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_FieldDefs(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FieldDefs() {
    this(fgbd4jJNI.new_FieldDefs__SWIG_0(), true);
  }

  public FieldDefs(long n) {
    this(fgbd4jJNI.new_FieldDefs__SWIG_1(n), true);
  }

  public long size() {
    return fgbd4jJNI.FieldDefs_size(swigCPtr, this);
  }

  public long capacity() {
    return fgbd4jJNI.FieldDefs_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    fgbd4jJNI.FieldDefs_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return fgbd4jJNI.FieldDefs_isEmpty(swigCPtr, this);
  }

  public void clear() {
    fgbd4jJNI.FieldDefs_clear(swigCPtr, this);
  }

  public void add(FieldDef x) {
    fgbd4jJNI.FieldDefs_add(swigCPtr, this, FieldDef.getCPtr(x), x);
  }

  public FieldDef get(int i) {
    return new FieldDef(fgbd4jJNI.FieldDefs_get(swigCPtr, this, i), false);
  }

  public void set(int i, FieldDef val) {
    fgbd4jJNI.FieldDefs_set(swigCPtr, this, i, FieldDef.getCPtr(val), val);
  }

}
