/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class GeometryDef {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GeometryDef(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GeometryDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_GeometryDef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeometryDef() {
    this(fgbd4jJNI.new_GeometryDef(), true);
  }

  public int GetGeometryType(int[] geometryType) {
    return fgbd4jJNI.GeometryDef_GetGeometryType(swigCPtr, this, geometryType);
  }

  public int SetGeometryType(GeometryType geometryType) {
    return fgbd4jJNI.GeometryDef_SetGeometryType(swigCPtr, this, geometryType.swigValue());
  }

  public int GetHasZ(boolean[] hasZ) {
    return fgbd4jJNI.GeometryDef_GetHasZ(swigCPtr, this, hasZ);
  }

  public int SetHasZ(boolean hasZ) {
    return fgbd4jJNI.GeometryDef_SetHasZ(swigCPtr, this, hasZ);
  }

  public int GetHasM(boolean[] hasM) {
    return fgbd4jJNI.GeometryDef_GetHasM(swigCPtr, this, hasM);
  }

  public int SetHasM(boolean hasM) {
    return fgbd4jJNI.GeometryDef_SetHasM(swigCPtr, this, hasM);
  }

  public int GetSpatialReference(SpatialReference spatialReference) {
    return fgbd4jJNI.GeometryDef_GetSpatialReference(swigCPtr, this, SpatialReference.getCPtr(spatialReference), spatialReference);
  }

  public int SetSpatialReference(SpatialReference spatialReference) {
    return fgbd4jJNI.GeometryDef_SetSpatialReference(swigCPtr, this, SpatialReference.getCPtr(spatialReference), spatialReference);
  }

}
