/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class Guid {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Guid(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Guid obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_Guid(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Guid() {
    this(fgbd4jJNI.new_Guid(), true);
  }

  public void SetNull() {
    fgbd4jJNI.Guid_SetNull(swigCPtr, this);
  }

  public void Create() {
    fgbd4jJNI.Guid_Create(swigCPtr, this);
  }

  public int FromString(String guidString) {
    return fgbd4jJNI.Guid_FromString(swigCPtr, this, guidString);
  }

  public int ToString(StringBuffer guidString) {
    return fgbd4jJNI.Guid_ToString(swigCPtr, this, guidString);
  }

  public boolean equal(Guid other) {
    return fgbd4jJNI.Guid_equal(swigCPtr, this, Guid.getCPtr(other), other);
  }

  public boolean notEqual(Guid other) {
    return fgbd4jJNI.Guid_notEqual(swigCPtr, this, Guid.getCPtr(other), other);
  }

  public void setData1(long value) {
    fgbd4jJNI.Guid_data1_set(swigCPtr, this, value);
  }

  public long getData1() {
    return fgbd4jJNI.Guid_data1_get(swigCPtr, this);
  }

  public void setData2(int value) {
    fgbd4jJNI.Guid_data2_set(swigCPtr, this, value);
  }

  public int getData2() {
    return fgbd4jJNI.Guid_data2_get(swigCPtr, this);
  }

  public void setData3(int value) {
    fgbd4jJNI.Guid_data3_set(swigCPtr, this, value);
  }

  public int getData3() {
    return fgbd4jJNI.Guid_data3_get(swigCPtr, this);
  }

  public void setData4(SWIGTYPE_p_unsigned_char value) {
    fgbd4jJNI.Guid_data4_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getData4() {
    long cPtr = fgbd4jJNI.Guid_data4_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

}
