/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class IndexDefs {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IndexDefs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexDefs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_IndexDefs(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IndexDefs() {
    this(fgbd4jJNI.new_IndexDefs__SWIG_0(), true);
  }

  public IndexDefs(long n) {
    this(fgbd4jJNI.new_IndexDefs__SWIG_1(n), true);
  }

  public long size() {
    return fgbd4jJNI.IndexDefs_size(swigCPtr, this);
  }

  public long capacity() {
    return fgbd4jJNI.IndexDefs_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    fgbd4jJNI.IndexDefs_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return fgbd4jJNI.IndexDefs_isEmpty(swigCPtr, this);
  }

  public void clear() {
    fgbd4jJNI.IndexDefs_clear(swigCPtr, this);
  }

  public void add(IndexDef x) {
    fgbd4jJNI.IndexDefs_add(swigCPtr, this, IndexDef.getCPtr(x), x);
  }

  public IndexDef get(int i) {
    return new IndexDef(fgbd4jJNI.IndexDefs_get(swigCPtr, this, i), false);
  }

  public void set(int i, IndexDef val) {
    fgbd4jJNI.IndexDefs_set(swigCPtr, this, i, IndexDef.getCPtr(val), val);
  }

}
