/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class PointShapeBuffer extends ShapeBuffer {
  private transient long swigCPtr;

  protected PointShapeBuffer(long cPtr, boolean cMemoryOwn) {
    super(fgbd4jJNI.PointShapeBuffer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PointShapeBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_PointShapeBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int GetPoint(SWIGTYPE_p_p_FileGDBAPI__Point point) {
    return fgbd4jJNI.PointShapeBuffer_GetPoint(swigCPtr, this, SWIGTYPE_p_p_FileGDBAPI__Point.getCPtr(point));
  }

  public int GetZ(SWIGTYPE_p_p_double z) {
    return fgbd4jJNI.PointShapeBuffer_GetZ(swigCPtr, this, SWIGTYPE_p_p_double.getCPtr(z));
  }

  public int GetM(SWIGTYPE_p_p_double m) {
    return fgbd4jJNI.PointShapeBuffer_GetM(swigCPtr, this, SWIGTYPE_p_p_double.getCPtr(m));
  }

  public int GetID(SWIGTYPE_p_p_int id) {
    return fgbd4jJNI.PointShapeBuffer_GetID(swigCPtr, this, SWIGTYPE_p_p_int.getCPtr(id));
  }

  public int Setup(ShapeType shapeType) {
    return fgbd4jJNI.PointShapeBuffer_Setup(swigCPtr, this, shapeType.swigValue());
  }

  public PointShapeBuffer() {
    this(fgbd4jJNI.new_PointShapeBuffer(), true);
  }

}
