/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class SpatialReferenceInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SpatialReferenceInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SpatialReferenceInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_SpatialReferenceInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAuth_name(String value) {
    fgbd4jJNI.SpatialReferenceInfo_auth_name_set(swigCPtr, this, value);
  }

  public String getAuth_name() {
    return fgbd4jJNI.SpatialReferenceInfo_auth_name_get(swigCPtr, this);
  }

  public void setAuth_srid(int value) {
    fgbd4jJNI.SpatialReferenceInfo_auth_srid_set(swigCPtr, this, value);
  }

  public int getAuth_srid() {
    return fgbd4jJNI.SpatialReferenceInfo_auth_srid_get(swigCPtr, this);
  }

  public void setSrtext(String value) {
    fgbd4jJNI.SpatialReferenceInfo_srtext_set(swigCPtr, this, value);
  }

  public String getSrtext() {
    return fgbd4jJNI.SpatialReferenceInfo_srtext_get(swigCPtr, this);
  }

  public void setSrname(String value) {
    fgbd4jJNI.SpatialReferenceInfo_srname_set(swigCPtr, this, value);
  }

  public String getSrname() {
    return fgbd4jJNI.SpatialReferenceInfo_srname_get(swigCPtr, this);
  }

  public SpatialReferenceInfo() {
    this(fgbd4jJNI.new_SpatialReferenceInfo(), true);
  }

}
