/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class SpatialReference {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SpatialReference(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SpatialReference obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_SpatialReference(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SpatialReference() {
    this(fgbd4jJNI.new_SpatialReference(), true);
  }

  public int GetSpatialReferenceText(StringBuffer spatialReference) {
    return fgbd4jJNI.SpatialReference_GetSpatialReferenceText(swigCPtr, this, spatialReference);
  }

  public int SetSpatialReferenceText(String spatialReference) {
    return fgbd4jJNI.SpatialReference_SetSpatialReferenceText(swigCPtr, this, spatialReference);
  }

  public int GetSpatialReferenceID(int[] srid) {
    return fgbd4jJNI.SpatialReference_GetSpatialReferenceID(swigCPtr, this, srid);
  }

  public int SetSpatialReferenceID(int srid) {
    return fgbd4jJNI.SpatialReference_SetSpatialReferenceID(swigCPtr, this, srid);
  }

  public int GetXYFalseOrigin(double[] falseX, double[] falseY) {
    return fgbd4jJNI.SpatialReference_GetXYFalseOrigin(swigCPtr, this, falseX, falseY);
  }

  public int SetXYFalseOrigin(double falseX, double falseY) {
    return fgbd4jJNI.SpatialReference_SetXYFalseOrigin(swigCPtr, this, falseX, falseY);
  }

  public int GetXYResolution(double[] xyResolution) {
    return fgbd4jJNI.SpatialReference_GetXYResolution(swigCPtr, this, xyResolution);
  }

  public int SetXYResolution(double xyResolution) {
    return fgbd4jJNI.SpatialReference_SetXYResolution(swigCPtr, this, xyResolution);
  }

  public int GetXYTolerance(double[] xyTolerance) {
    return fgbd4jJNI.SpatialReference_GetXYTolerance(swigCPtr, this, xyTolerance);
  }

  public int SetXYTolerance(double xyTolerance) {
    return fgbd4jJNI.SpatialReference_SetXYTolerance(swigCPtr, this, xyTolerance);
  }

  public int GetZFalseOrigin(double[] falseZ) {
    return fgbd4jJNI.SpatialReference_GetZFalseOrigin(swigCPtr, this, falseZ);
  }

  public int SetZFalseOrigin(double falseZ) {
    return fgbd4jJNI.SpatialReference_SetZFalseOrigin(swigCPtr, this, falseZ);
  }

  public int GetZResolution(double[] zResolution) {
    return fgbd4jJNI.SpatialReference_GetZResolution(swigCPtr, this, zResolution);
  }

  public int SetZResolution(double zResolution) {
    return fgbd4jJNI.SpatialReference_SetZResolution(swigCPtr, this, zResolution);
  }

  public int GetZTolerance(double[] zTolerance) {
    return fgbd4jJNI.SpatialReference_GetZTolerance(swigCPtr, this, zTolerance);
  }

  public int SetZTolerance(double zTolerance) {
    return fgbd4jJNI.SpatialReference_SetZTolerance(swigCPtr, this, zTolerance);
  }

  public int GetMFalseOrigin(double[] falseM) {
    return fgbd4jJNI.SpatialReference_GetMFalseOrigin(swigCPtr, this, falseM);
  }

  public int SetMFalseOrigin(double falseM) {
    return fgbd4jJNI.SpatialReference_SetMFalseOrigin(swigCPtr, this, falseM);
  }

  public int GetMResolution(double[] mResolution) {
    return fgbd4jJNI.SpatialReference_GetMResolution(swigCPtr, this, mResolution);
  }

  public int SetMResolution(double mResolution) {
    return fgbd4jJNI.SpatialReference_SetMResolution(swigCPtr, this, mResolution);
  }

  public int GetMTolerance(double[] mTolerance) {
    return fgbd4jJNI.SpatialReference_GetMTolerance(swigCPtr, this, mTolerance);
  }

  public int SetMTolerance(double mTolerance) {
    return fgbd4jJNI.SpatialReference_SetMTolerance(swigCPtr, this, mTolerance);
  }

}
