/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ch.ehi.fgdb4j.jni;

public class Table {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Table(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Table obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fgbd4jJNI.delete_Table(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int GetDefinition(StringBuffer tableDef) {
    return fgbd4jJNI.Table_GetDefinition(swigCPtr, this, tableDef);
  }

  public int GetDocumentation(StringBuffer documentation) {
    return fgbd4jJNI.Table_GetDocumentation(swigCPtr, this, documentation);
  }

  public int SetDocumentation(String documentation) {
    return fgbd4jJNI.Table_SetDocumentation(swigCPtr, this, documentation);
  }

  public int GetFieldInformation(FieldInfo fieldInfo) {
    return fgbd4jJNI.Table_GetFieldInformation(swigCPtr, this, FieldInfo.getCPtr(fieldInfo), fieldInfo);
  }

  public int GetFields(FieldDefs fieldDefs) {
    return fgbd4jJNI.Table_GetFields(swigCPtr, this, FieldDefs.getCPtr(fieldDefs), fieldDefs);
  }

  public int AddField(String fieldDef) {
    return fgbd4jJNI.Table_AddField__SWIG_0(swigCPtr, this, fieldDef);
  }

  public int AddField(FieldDef fieldDef) {
    return fgbd4jJNI.Table_AddField__SWIG_1(swigCPtr, this, FieldDef.getCPtr(fieldDef), fieldDef);
  }

  public int AlterField(String fieldDef) {
    return fgbd4jJNI.Table_AlterField(swigCPtr, this, fieldDef);
  }

  public int DeleteField(String fieldName) {
    return fgbd4jJNI.Table_DeleteField(swigCPtr, this, fieldName);
  }

  public int GetIndexes(SWIGTYPE_p_std__vectorT_std__string_t indexDefs) {
    return fgbd4jJNI.Table_GetIndexes__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(indexDefs));
  }

  public int GetIndexes(IndexDefs indexDefs) {
    return fgbd4jJNI.Table_GetIndexes__SWIG_1(swigCPtr, this, IndexDefs.getCPtr(indexDefs), indexDefs);
  }

  public int AddIndex(String indexDef) {
    return fgbd4jJNI.Table_AddIndex__SWIG_0(swigCPtr, this, indexDef);
  }

  public int AddIndex(IndexDef indexDef) {
    return fgbd4jJNI.Table_AddIndex__SWIG_1(swigCPtr, this, IndexDef.getCPtr(indexDef), indexDef);
  }

  public int DeleteIndex(String indexName) {
    return fgbd4jJNI.Table_DeleteIndex(swigCPtr, this, indexName);
  }

  public int CreateSubtype(String subtypeDef) {
    return fgbd4jJNI.Table_CreateSubtype(swigCPtr, this, subtypeDef);
  }

  public int AlterSubtype(String subtypeDef) {
    return fgbd4jJNI.Table_AlterSubtype(swigCPtr, this, subtypeDef);
  }

  public int DeleteSubtype(String subtypeName) {
    return fgbd4jJNI.Table_DeleteSubtype(swigCPtr, this, subtypeName);
  }

  public int EnableSubtypes(String subtypeFieldName, String subtypeDef) {
    return fgbd4jJNI.Table_EnableSubtypes(swigCPtr, this, subtypeFieldName, subtypeDef);
  }

  public int GetDefaultSubtypeCode(int[] defaultCode) {
    return fgbd4jJNI.Table_GetDefaultSubtypeCode(swigCPtr, this, defaultCode);
  }

  public int SetDefaultSubtypeCode(int defaultCode) {
    return fgbd4jJNI.Table_SetDefaultSubtypeCode(swigCPtr, this, defaultCode);
  }

  public int DisableSubtypes() {
    return fgbd4jJNI.Table_DisableSubtypes(swigCPtr, this);
  }

  public int Search(String subfields, String whereClause, Envelope envelope, boolean recycling, EnumRows rows) {
    return fgbd4jJNI.Table_Search__SWIG_0(swigCPtr, this, subfields, whereClause, Envelope.getCPtr(envelope), envelope, recycling, EnumRows.getCPtr(rows), rows);
  }

  public int Search(String subfields, String whereClause, boolean recycling, EnumRows rows) {
    return fgbd4jJNI.Table_Search__SWIG_1(swigCPtr, this, subfields, whereClause, recycling, EnumRows.getCPtr(rows), rows);
  }

  public int CreateRowObject(Row row) {
    return fgbd4jJNI.Table_CreateRowObject(swigCPtr, this, Row.getCPtr(row), row);
  }

  public int Insert(Row row) {
    return fgbd4jJNI.Table_Insert(swigCPtr, this, Row.getCPtr(row), row);
  }

  public int Update(Row row) {
    return fgbd4jJNI.Table_Update(swigCPtr, this, Row.getCPtr(row), row);
  }

  public int Delete(Row row) {
    return fgbd4jJNI.Table_Delete(swigCPtr, this, Row.getCPtr(row), row);
  }

  public int IsEditable(boolean[] isEditable) {
    return fgbd4jJNI.Table_IsEditable(swigCPtr, this, isEditable);
  }

  public int GetRowCount(int[] rowCount) {
    return fgbd4jJNI.Table_GetRowCount(swigCPtr, this, rowCount);
  }

  public int GetExtent(Envelope extent) {
    return fgbd4jJNI.Table_GetExtent(swigCPtr, this, Envelope.getCPtr(extent), extent);
  }

  public int SetWriteLock() {
    return fgbd4jJNI.Table_SetWriteLock(swigCPtr, this);
  }

  public int FreeWriteLock() {
    return fgbd4jJNI.Table_FreeWriteLock(swigCPtr, this);
  }

  public int LoadOnlyMode(boolean loadOnlyMode) {
    return fgbd4jJNI.Table_LoadOnlyMode(swigCPtr, this, loadOnlyMode);
  }

  public Table() {
    this(fgbd4jJNI.new_Table(), true);
  }

}
